### ISSUE TITLE
The Qolsys Panel interactions - EXIT_DELAY

### ISSUE THREAD

**Issue by EHylands** [XaF/qolsysgw#76]
Salut XaF,

Just started playing around with my IQ2+ panel (2.6.1 for the moment).

Found out the 'ALARM' event will always report 'EXIT_DELAY' when panel is in Arm Stay Exit Delay or Arm Away Exit Delay.

At the same moment, if I manually send an INFO SUMMARY update during the exit delay period, I will receive one of the 2 following partition states
- ARM-AWAY-EXIT-DELAY
- ARM-STAY-EXIT-DELAY

I saw the following line in your Readme file:
`EXIT_DELAY when the alarm is arming, giving time to leave the place before being armed (also ARM-AWAY-EXIT-DELAY on some panels, it seems)`

Do you know which panels are sending 'EXIT_DELAY' and which one are sending ARM-AWAY-EXIT-DELAY and ARM-STAY-EXIT-DELAY ?

Is it possible that:
- ALARM event reports 'EXIT_DELAY' all the time
- INFO SUMMARY update reports ARM-AWAY-EXIT-DELAY and ARM-STAY-EXIT-DELAY

Merci! 
EH

**Comment by XaF** [comment]
Allô Eric!

This might very well be the case! I have not witnessed the `ARM-AWAY-EXIT-DELAY` or `ARM-STAY-EXIT-DELAY` myself, and simply added support as I saw them in some other implementations (actually just the first one, and that makes me think now that I should probably include the second one!)

I believe your interpretation of having those in the `SUMMARY` makes sense, as they'd be providing information to the actual current state of the panel (it's exit delay, but what's to come after). I'll make an update to the documentation to reflect that. Merci ! :o)

Since you're playing around with things at the moment, please do let me know if you find anything I might have missed! I'm trying to have that documentation as accurate as possible so it makes things easy for development of this and other integrations (whether for Home Assistant or others), and make sure that `qolsysgw` includes as much of the features as possible!
